---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: ecoplan
spec:
  encryptedData:
    token: AgCvjcb6dB/NkGzawVPunq0L/PEIYsy8Ju/esmm6pgpnR8BXFjXp9S3kLH77XaE01TcbWUtiKFYwh24wUA91iRXx1LtbyLFLT9iyiXted5RUZFtHuicSIDVvdjJ9P6QRTQpZY3SzsTZmuPwecXdeLnK8QMiQ14ILP8S//JNmaENdqSg4F1056Zf1+dDE/n8//Ye0Dvdn/ue9/8VDTz3OlOE70Cz8Y9FBFjY4rjq/Nbqj8ZFCnKnOWG1jYN0EU4uXPvJr1ze6GNdx4CHaCAdMeEGyhOvXZxYJL5B9xDBqrHPcQPZwJ6USZmlLB9dTHZpgaejQQy4Ko9bNX8sN31L/YSHGZttbHTDQzVy90piJAg1SCO5QdT/xID/IojDMxkmhb4w56CWgiX4Rie5swETZcXCqD0WpMNawrQZ9dr0gg830JVbGb0L2b/195qBj7b85AWPvKvzC1zIkeucEE5bCZhOb/MRK4fxSc8PVppusX7qcFjwgOz+hr8mFHKfwi2477Bsefxfrh72GYnrOC2sR25GXgtZ40TrTl4cuJi20W839r4lIzTsBFx2iAlkbP34DRdzTSbB428o9mfQARdWbLyRYFmQ6wdeFDKuJ5uwK7Xij6bvySqab92xEzX+GpMu/5Ozp1zwgEV6zC6Otza1MSO6cNhrjdTDfpxH5CvdopYBzJ63Te99uk1c5ybMMfoAx3dFjkpyAOMeoeWVD08ZhXaxUIft1mWFk7voefUazwV0wv4gMdlYT9073FGOh32fP1jww7XcTJ93GeNvR1v9tHf1vBG1d9jpsKFuBuWIlvPDM8gnPq9BkZ92TxUCwRBTLxjfz678wO1TTWYTOH3mQYLpaVTPVV1mA8OwSOv4zFmXQfyL/W/oLQRYPxwg9UovULhtboa4ZE7uxHMd85eV7GPeDB5BgAOSHvstnbgZbwZW4WUupJsY=
  template:
    metadata:
      name: cloudflared-token
      namespace: ecoplan
