apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: ecoplan
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
        uid: prometheus

      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        uid: loki

      - name: Tempo
        type: tempo
        url: http://tempo:3200
        access: proxy
        uid: tempo
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
          lokiSearch:
            datasourceUid: loki
          serviceMap:
            datasourceUid: prometheus
