---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: ecoplan
spec:
  encryptedData:
    admin-password: AgBkucf4tZNXsgzU3wouOGCVqheGvH6oaOJue/EP4fOMy4gIG8jURufh4Il4qceYIdElPptIDTv3N3VKuG/AXXIydoqtwLMTKO1rICrz5DDevQs4t32kCqPX31CzN3L/cWxdSqFjWGl2cIfOnQSQkbQtIx6IFWKXn1PIqSrWWWlRwz00A3LqRIKYoKCIzckEPLI9GcpUgiHphDjS8urT2ly8o++4gAA20NmRWPat/6oQt4xJVRgId+lJX2BD3B0oOm7gEVuCG9nn+lbOVua2FLmrYc1oT57aEUXHHgKydvHtMN9KqFS4XhNe5yUn5iR/Qn/rkDqne74Jws1QOh/+VIQyNuFM860ytFus8JvGiwP8g2yv/u8NLx82yin5CyScgV9ORWfraY49zOR9j4E5K1RdRRaEpZWJ7IZZcu7GtLAc7H68OIsGBsToSooXTqdiutNFmJ62xr8y3orCXQMM4lbPl0jGCEZLUAW+RL1PlsSFQuA36H6p5NML6V4s5RAP4NTiij9w602HuARoB1O48qhjkTs/gwSdJ7Yt6nN6IygpZUj88nQhrLm0NC9aPrtgYkWX9cwWfjePc8QURs1y0dGcasVe0glbeF9etb5pI6Zh0vBCzSASgb9dteFWtCMfU7ol5z062mKwHGql0wLHhu7M2KK/6bjl/DmXPiSXgKrXkTBQlx81YXAOFaYyv7xe2hr0eCOOHzisxOA3NE3DaEG9UuPXkPY8CqmkI39WwPeWIA==
  template:
    metadata:
      name: grafana-secret
      namespace: ecoplan
