apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecoplan
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ecoscan-uk/infra
    targetRevision: trunk
    path: deploy/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ecoplan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
