apiVersion: v1
kind: Service
metadata:
  name: ecoscan-service
  namespace: ecoplan
  labels:
    app: ecoscan-service
spec:
  selector:
    app: ecoscan-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      appProtocol: grpc
    - name: metrics
      port: 9090
      targetPort: 9090
